# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'strava' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for strava
pod 'OAuthSwift', '~> 1.2.0'
  target 'stravaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'stravaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
